config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#show'
  get 'external_payments', to: 'payments#external_payment'
  resources :user, only: [:show]
  resources :payments, except: [:show]
  resources :groups, except: [:destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :payments_groups, dependent: :destroy
  has_many :payments, through: :payments_groups

  validates :name, presence: true
  validates :icon, presence: true

  mount_uploader :icon, ImageUploader
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :payments_groups, dependent: :destroy
  has_many :groups, through: :payments_groups

  validates :name, presence: true, length: { minimum: 4, message: 'Transaction name should be at lest 4 letters.' }
  validates :amount, presence: true
end

app/models/payments_group.rb
class PaymentsGroup < ApplicationRecord
  belongs_to :group
  belongs_to :payment
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user

  has_many :travel_groups, dependent: :destroy
  has_many :groups, through: :travel_groups

  validates :purpose, presence: true, length: { in: 4..40 }
  validates :source, presence: true, length: { in: 2..20 }
  validates :destination, presence: true, length: { in: 2..20 }
  validates :distance, presence: true

  scope :recent_first, -> { order('created_at DESC') }
end

app/models/travel_group.rb
class TravelGroup < ApplicationRecord
  belongs_to :travel
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :payments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :permitted_params, if: :devise_controller?

  protected

  def permitted_params
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @groups = Group.includes(:user).paginate(page: params[:page], per_page: 2).order(:name)
  end

  def show
    @group = Group.find(params[:id])
    @group_payments = @group.payments.paginate(page: params[:page], per_page: 2).order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      flash[:success] = 'Group created'
      redirect_to @group
    else
      flash.now[:alert] = 'Group was not created'
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show update destroy edit]
  before_action :authenticate_user!

  def index
    # rubocop:disable Layout/HashAlignment
    @payments = Payment.includes(:groups).paginate(page: params[:page],
                    per_page: 2).where(user_id: current_user.id).joins(:groups)
    # rubocop:enable Layout/HashAlignment
    @payment_sum = Payment.where(user_id: current_user.id).joins(:groups).sum(:amount)
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = current_user.payments.build(payment_params)
    if @payment.save
      group_id = params[:payment][:group_id]
      PaymentsGroup.create(group_id: group_id, payment_id: @payment.id) if group_id
      flash[:success] = 'You created new payment'
      redirect_to root_path
    else
      flash.now[:alert] = 'payment was not created'
      render :new
    end
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    payment = Payment.find(params[:id])
    if payment.update(payment_params)
      flash[:success] = 'You updated your payment'
      redirect_to root_path
    else
      flash[:alert] = 'payment was not updated'
      render :edit
    end
  end

  def destroy
    Payment.find(params[:id]).destroy
    flash[:success] = 'payment deleted'
    redirect_to root_path
  end

  def external_payment
    # rubocop:disable Layout/HashAlignment
    @external_payments = Payment.includes(:groups).paginate(page: params[:page],
    per_page: 2).where(user_id: current_user.id).left_outer_joins(:groups).where('groups.id IS NULL')
    # rubocop:enable Layout/HashAlignment
    @exp_sum = Payment.where(user_id: current_user.id).left_outer_joins(:groups).where('groups.id IS NULL').sum(:amount)
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, :user_id)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: %i[show edit update destroy]

  def index
    @travels = my_travels
    @total_distance = current_user.travels.pluck(:distance).sum
  end

  def show; end

  def new
    @travel = Travel.new
  end

  def edit; end

  def create
    @travel = current_user.travels.build(travel_params)

    if @travel.save
      @travel.travel_groups.create(show_group_id)
      redirect_to travels_path, notice: 'Travel was successfully created.'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @travel.update(travel_params)

      if show_group_id[:group_id]
        if @travel.groups.empty?
          @travel.travel_groups.create(show_group_id)
        else
          @travel.travel_groups.update(show_group_id)
        end
      end

      redirect_to @travel, notice: 'Travel was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @travel.destroy
    redirect_to travels_path, notice: 'Travel was successfully destroyed'
  end

  def external_travel
    @external = my_travels.left_joins(:travel_groups).where('group_id IS NULL')
    @total_distance = @external.sum(:distance)
  end

  private

  def set_travel
    @travel = Travel.find(params[:id])
  end

  def travel_params
    params.require(:travel).permit(:purpose, :source, :destination, :distance, :user_id, group_ids: [])
  end

  def show_group_id
    params.require(:travel).permit(:group_id)
  end

  def my_travels
    current_user.travels.includes(:groups).recent_first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = '')
    base_title = 'Transaction app'
    if title.empty?
      base_title
    else
      title + ' | '.concat(base_title)
    end
  end
end

app/helpers/bootstrap_icons_helper.rb
module BootstrapIconsHelper
  def icon(icon, options = {})
    file = File.read("node_modules/bootstrap-icons/icons/#{icon}.svg")
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    svg['class'] += ' '.concat(options[:class]) if options[:class].present?
    doc.to_html.html_safe
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
  def travel_icon(travel)
    if travel.groups.first.nil?
      image_tag 'travel_icon.jpg', class: 'travel_item_icon'
    elsif !travel.groups.first.icon.attached?
      image_tag 'travel_icon.jpg', class: 'travel_item_icon'
    else
      image_tag travel.groups.first.icon, class: 'travel_item_icon'
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_avatar
    if current_user.profile_pic.attached?
      image_tag current_user.profile_pic, class: 'circle responsive-img profile_img'
    else
      image_tag 'blank_profile.png', class: 'circle responsive-img profile_img'
    end
  end
end

app/views/groups/_form.html.erb
<div>
<%= form_with(model: @group, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :icon %>
  <%= f.file_field :icon, class: 'form-control-file' %>
  </div>
  
  <%= f.submit 'Submit', class: 'btn btn-primary btn__sign mt-4' %>
  
<% end %>
</div>

app/views/groups/_group.html.erb
 <div class='list-group mt-3'>
        <div class=' list-group-item list-group-item-action'>
            <div class='d-flex align-items-center justify-content-between'>
                <div class='d-flex align-items-center'>
                  <img src="<%=group.icon%>" class="size rounded"/>
                  <h5>
                    <%= link_to group.name, group ,class:'ml-2 text-lg' %>
                  </h5>
                </div>
            </div>
            <hr>
            <div class='d-flex justify-content-between align-items-center'>
                  <h6>Group by: <%= group.user.name %> </h6>
                   <h6><%= group.created_at.strftime("%d %B %Y") %> </h6>
            </div>
           
        </div>
    </div>

app/views/groups/_group_travel.html.erb
<ul class="collection">
  <li class="collection-item avatar">
    <div class="row travel_tile">
      <div class="col s2">
        <%= travel_icon(gt) %>
      </div>
      <div class="col s10">
          <span class="title pink-text accent-4">
            <%= gt.user.name %>
            <span> | </span>
            <%= gt.user.employee_id.upcase %>
          </span>
        <div class="left-align">
          <p><span class="teal-text">Purpose:</span> <%= gt.purpose %></p>
          <p><span class="teal-text">Source:</span> <%= gt.source %> </p>
          <p><span class="teal-text">Destination:</span> <%= gt.destination %></p>
          <p><span class="teal-text">Date:</span> <%= gt.created_at.to_s(:long_ordinal) %></p>
        </div>
      </div>
    </div>

    <h3 class="secondary-content">
      <%= gt.distance %>
      <span class="km">km</span>
    </h3>

    <div>
      <%= link_to '<i class="small material-icons indigo-text darken-4">visibility</i>'.html_safe, gt %>
      <%= edit_travel_link(gt) %>
      <%= delete_travel_link(gt) %>
    </div>
  </li>
</ul>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<%= provide(:title,'All groups') %>
<h1 class='text-center pt-4'>All groups</h1>

<div class='p-4'>
<%= render @groups%>

<%= link_to 'Create new', new_group_path, class: 'btn btn-primary btn__sign my-3' %>

<div class='d-flex justify-content-between align-items-center'>
    <%= link_to icon("arrow-left-square", class: "text-danger main__icon"), root_path %>
     <%= will_paginate @groups, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
</div>

app/views/groups/new.html.erb
<%= provide(:title,'Create Group') %>
<div class='bg-white  p-4'>
  <h2 class='text-center'>New group</h2>

  <%= render 'form', group: @group %>

  <div class='mt-3'>
    <%= link_to icon("arrow-left-square", class: "text-danger main__icon"),groups_path %>
  </div>
</div>

app/views/groups/show.html.erb
<%= provide(:title, @group.name) %>
<div class='p-4'>
  <div class='d-flex justify-content-center align-items-center'>
    <img src="<%=@group.icon%>" class="size rounded"/>
    <h2  class='ml-2'><%= @group.name %></h2>
  </div>
    <hr>
    <% @group_payments.each do |g| %>
    <div class='list-group  mt-3'>
        <div class='list-group-item list-group-item-action'>
            <div class='d-flex justify-content-between align-items-center'>
                <div class='d-flex align-items-center'>
                  <img src="<%=@group.icon%>" class="size rounded"/>
                   <h5 class='ml-2'> <%=  g.name %></h5>
                </div>
                <h5><%= number_to_currency(g.amount) %></h5>
            </div>
            <hr>
            
            <div class='d-flex justify-content-between'>
              <span>Transaction by: <%= g.user.name %></span>
              <span><%= g.created_at.strftime("%d %B %Y") %></span>
            </div>
        
        </div>
    </div>
    <% end %>
   <div class='d-flex justify-content-between align-items-center mt-3'>
      <%= link_to icon("arrow-left-square", class: "text-danger main__icon"),groups_path %>
       <%= will_paginate @group_payments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
   </div>
</div>

app/views/layouts/_flash.html.erb
 <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="alert alert-success">
         <ul>
            <li>
              <%= msg %>
            </li>
         </ul>
        </div>
        
      <% elsif type == "alert" %>
        <div class="alert alert-danger">
           <ul>
            <li>
              <%= msg %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class='alert alert-<%= "#{type}" %>'>
         <ul>
            <li>
              <%= msg %>
            </li>
          </ul>
        </div>
      <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer light-blue darken-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text brand-logo">TravelBlog</h5>
        <p class="grey-text text-lighten-4">
          A simple website to log your travel data.
        </p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5>
          <%= link_to 'Home', root_path, class: 'white-text' %>
        </h5>
        <ul>
          <li><%= link_to 'All Travel Logs', travels_path, class: 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'All External Travel Logs', external_path, class: 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'All Groups', groups_path, class: 'grey-text text-lighten-3' %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2021 Uduak John
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
    <div class=" container navbar header__box  fixed-top navbar-light ">
     <div class="container d-flex align-items-center">   
       <%= link_to "transaction app",root_path, id: "logo" %>
        <div class=''>
         <% if current_user %>
                <%= link_to "Log out", destroy_user_session_path, method:"delete", class: 'text-lg text-white' %>
          <% else %>
                 <%= link_to "Log in", new_user_session_path, class: 'text-white mx-2 text-lg' %>
                 <%= link_to "Sign up", new_user_registration_path, class:'text-white text-lg' %>
          <% end %>
        </div>
        </div>
    </div>
      

app/views/layouts/_messages.html.erb
<%= message notice, 'green' %>

<%= message alert, 'red' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
  <div class='container bg-white p-4  h-100 border'>
 
    <%= render 'layouts/flash' %>
    <%= yield %>

  </div>
  </body>
</html>

app/views/payments/_form.html.erb
<div>
<%= form_with(model: @payment, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
      <%= f.label :group %>
      <%= f.collection_select :group_id, Group.all, :id, :name, {prompt: 'Select group'}, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, class: 'form-control' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-primary btn__sign mt-4' %>
  
<% end %>
</div>

app/views/payments/_payment.html.erb
<div class='list-group mt-3'>
        <div class='list-group-item list-group-item-action'>
            <div class='d-flex justify-content-between align-items-center'>
                <div class='d-flex align-items-center'>
                   <h5 class='ml-2'> <%=  payment.name %></h5>
                </div>
                <h5><%= number_to_currency(payment.amount) %></h5>
            </div>
            <hr>
            
            <div class='d-flex justify-content-between'>
              <div>
                <%= link_to icon("trash", class: "text-danger main__icon"), payment, method: :delete, data: { confirm: 'Are you sure' } %>
                <%= link_to icon("arrow-repeat", class: "text-success main__icon"), edit_payment_path(payment)  %>
              </div>
              <span><%= payment.created_at.strftime("%d %B %Y") %></span>
            </div>
        
        </div>
    </div>

app/views/payments/edit.html.erb
<%= provide(:title,'Edit Transaction') %>
<div class='bg-white  p-4'>
<h2>Edit Transaction</h2>

<%= render 'form', payment: @payment %>
   <div class='mt-3'>
      <%= link_to icon("arrow-left-square", class: "text-danger main__icon"), payments_path %>
    </div>

</div>

app/views/payments/external_payment.html.erb
<%= provide(:title, 'External transactions') %>
<div class='p-4'>
<h5 class='my-3'>Total amount: <%= number_to_currency(@exp_sum) %></h5>
    <%= render @external_payments%>

<%= link_to 'Add new', new_payment_path, class: 'btn btn-primary btn__sign my-3' %>
<div class='d-flex justify-content-between align-items-center'>
    <%= link_to icon("arrow-left-square", class: "text-danger main__icon"), root_path %>
     <%= will_paginate @external_payments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
</div>

app/views/payments/index.html.erb
<%= provide(:title,'Transactions') %>
<div class='p-4'>
<h5 class='my-3'>Total amount: <%= number_to_currency(@payment_sum) %></h5>
    <% @payments.each do |p| %>
    <div class='list-group mt-3'>
        <div class='list-group-item list-group-item-action'>
            <div class='d-flex justify-content-between align-items-center'>
                <div class='d-flex align-items-center'>
                  <img src="<%= p.groups.take.icon %>" class="size rounded"/>
                   <h5 class='ml-2'> <%=  p.name %></h5>
                </div>
                <h5><%= number_to_currency(p.amount) %></h5>
            </div>
            <hr>
            
            <div class='d-flex justify-content-between'>
              <div>
                <%= link_to icon("trash", class: "text-danger main__icon"), p, method: :delete, data: { confirm: 'Are you sure' } %>
                <%= link_to icon("arrow-repeat", class: "text-success main__icon"), edit_payment_path(p)  %>
              </div>
              <span><%= p.created_at.strftime("%d %B %Y") %></span>
            </div>
        
        </div>
    </div>
<% end %>

<%= link_to 'Add new', new_payment_path, class: 'btn btn-primary btn__sign my-3' %>
<div class='d-flex justify-content-between align-items-center'>
    <%= link_to icon("arrow-left-square", class: "text-danger main__icon"), root_path %>
     <%= will_paginate @payments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
</div>

app/views/payments/new.html.erb
<%= provide(:title,'Create Transaction') %>
<div class='bg-white  p-4'>
<h2>New transaction</h2>

  <%= render 'form', payment: @payment %>

  <div class='mt-3'>
    <%= link_to icon("arrow-left-square", class: "text-danger main__icon"), payments_path %>
    <%= link_to 'Create group', new_group_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The forms contains <%= pluralize(object.errors.count,"erorr") %>.
        </div>
        <ul>
            <%= object.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/travels/_distance_sum.html.erb
<div class="col s12 m7">
  <div class="card horizontal">
    <div class="card-stacked">
      <div class="card-content row secondary-content pink-text accent-4">
        <h3 class="col s8 left-align">Total Distance Travelled: </h3>
        <h3 class="col s4 right-align">
          <%= distance %>
          <span class="km"> km</span>
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/travels/_form.html.erb
<div class="col s12">
  <div class="card horizontal left-align">
    <div class="card-stacked">
      <div class="card-content">

        <%= form_with(model: travel) do |form| %>

          <%= error_messages_for(travel) %>

          <%= form.text_field :purpose, placeholder: 'Purpose' %>
          <%= form.text_field :source, placeholder: 'Source' %>
          <%= form.text_field :destination, placeholder: 'Destination' %>
          <%= form.number_field :distance, placeholder: 'Distance (in km)' %>

          <%= form.collection_check_boxes( :group_ids, Group.all, :id, :name ) %>

          <br/>
          <br/>
          <div class="btn waves-effect waves-light center">
            <%= form.submit %>
          </div>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to '<i class="small material-icons green-text darken-4">arrow_back</i>'.html_safe, travels_path %>
      </div>
    </div>
  </div>
</div>

app/views/travels/_my_travels.html.erb
<div class="fixed-action-btn">
    <span class="btn-floating pulse btn-large red">
      <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_travel_path %>
    </span>
</div>

<%= render my_travels %>

app/views/travels/_travel.html.erb
<ul class="collection">
  <li class="collection-item avatar">
    <div class="row travel_tile">
      <div class="col s2">
        <%= travel_icon(travel) %>
      </div>
      <div class="col s10">
          <span class="title pink-text accent-4">
            <%= travel.user.name %>
            <span> | </span>
            <%= travel.user.employee_id.upcase %>
          </span>
        <div class="left-align">
          <p><span class="teal-text">Purpose:</span> <%= travel.purpose %></p>
          <p><span class="teal-text">Source:</span> <%= travel.source %> </p>
          <p><span class="teal-text">Destination:</span> <%= travel.destination %></p>
          <p><span class="teal-text">Date:</span> <%= travel.created_at.to_s(:long_ordinal) %></p>
        </div>
      </div>
    </div>

    <h3 class="secondary-content">
      <%= travel.distance %>
      <span class="km">km</span>
    </h3>

    <div>
      <%= link_to '<i class="small material-icons indigo-text darken-4">visibility</i>'.html_safe, travel %>
      <%= link_to '<i class="small material-icons teal-text darken-4">mode_edit</i>'.html_safe, edit_travel_path(travel) %>
      <%= link_to '<i class="small material-icons deep-orange-text accent-3">delete</i>'.html_safe, travel, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </li>
</ul>

app/views/travels/edit.html.erb
<h1>Editing Travel</h1>

<%= render 'form', travel: @travel %>

app/views/travels/external_travel.html.erb
<%= render 'distance_sum', distance: @total_distance %>

<%= render 'my_travels', my_travels: @external %>

app/views/travels/index.html.erb
<%= render 'distance_sum', distance: @total_distance %>

<%= render 'my_travels', my_travels: @travels %>

app/views/travels/new.html.erb
<h1>Create New Travel Log</h1>

<%= render 'form', travel: @travel %>

app/views/travels/show.html.erb
<div class="card blue lighten-5">
  <div class="card-content teal-text darken-4">
    <%= travel_icon(@travel) %>
    <span class="card-title pink-text accent-1"><%= @travel.purpose %></span>
    <p class="travel_show_text"><span class="brown-text darken-4">From:</span> <%= @travel.source %></p>
    <p class="travel_show_text"><span class="brown-text darken-4">To:</span> <%= @travel.destination %></p>
    <p class="travel_show_text"><span class="brown-text darken-4">Distance Travelled:</span> <%= @travel.distance %><span>km</span></p>
    <p class="travel_show_text"><span class="brown-text darken-4">Date:</span> <%= @travel.created_at.to_s(:long_ordinal) %></p>
  </div>
  <div class="card-action right-align">
    <%= link_to '<i class="small material-icons green-text darken-4">arrow_back</i>'.html_safe, external_path %>
    <%= link_to '<i class="small material-icons">mode_edit</i>'.html_safe, edit_travel_path(@travel) %>
    <%= link_to '<i class="small material-icons red-text accent-3">delete</i>'.html_safe, @travel, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="row">
  <div class="col s12">
    <div class="card light-blue darken-1">
      <div class="card-content white-text">

        <%= profile_avatar %>

        <span class="btn-floating btn-large amber lighten-1">
          <%= link_to '<i class="large material-icons red-text">mode_edit</i>'.html_safe, edit_user_registration_path %>
        </span>

        <div class="profile_info">
          <p class="profile_info_name"><%= current_user.name %></p>
          <p><%= current_user.employee_id.upcase %></p>
          <p><%= current_user.email %></p>
        </div>
      </div>

      <div class="left-align profile_links">
          <p>
            <i class="material-icons white-text profile_icon">airplanemode_active</i>
            <%= link_to 'All my Travel-logs', travels_path, class: 'profile_link' %>
          </p>
          <p>
            <i class="material-icons white-text profile_icon">airplanemode_inactive</i>
            <%= link_to 'All my External Travel-logs', external_path, class: 'profile_link' %>
          </p>
          <p>
            <i class="material-icons white-text profile_icon">people</i>
            <%= link_to 'All groups', groups_path, class: 'profile_link' %>
          </p>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title,current_user.name) %>
<div class='row'>
<div class='col-md-6 mx-auto alert alert-primary'>
<div class='d-flex flex-column justify-content-center mx-auto my-3 '>
  <%= image_tag("avatar.png", width:100, class:'mx-auto') %>
  <h1 class='text-center mt-2'> Hi there, <%= current_user.name %>! </h1>
</div>
<div class='list-group my-3'>
  <div class='list-group-item list-group-item-action rounded bg-primary'>
    <%= link_to 'All my transactions', payments_path, class: 'text-lg text-white' %>
  </div>
  <div class='list-group-item list-group-item-action my-3 bg-primary rounded'>
      <%= link_to 'All my external transactions', external_payments_path, class: 'text-lg text-white' %>
  </div>
  <div class='list-group-item list-group-item-action  bg-primary rounded'>
      <%= link_to 'All groups', groups_path, class: 'text-lg text-white' %>
  </div>
</div>
</div>

</div>

  